blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/ashishyd/env-type-generator/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/ashishyd/env-type-generator#readme
    about: Read the full documentation
